name: gaussian_splatting
channels:
  - rapidsai
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - rapids=24.06
  - python=3.11
  - cuda-version=12.1
  - plyfile=0.8.1
  - pytorch==2.2.2
  - torchvision==0.17.2
  - torchaudio==2.2.2
  - pip
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn